In [1]:
import pandas as pd
import numpy as np

In [10]:
df = pd.DataFrame(
    {"A": [1, 2],
     "B": [3, 4]}
)

df

A  B
0  1  3
1  2  4

In [12]:
df.to_numpy()

array([[1, 3],
       [2, 4]])

In [13]:
df = pd.DataFrame({"A": [1, 2], "B": [3.0, 4.5]})
df

A    B
0  1  3.0
1  2  4.5

In [14]:
df.to_numpy()

array([[1. , 3. ],
       [2. , 4.5]])

In [15]:
df['C'] = pd.date_range('2000', periods=2)
df

A    B          C
0  1  3.0 2000-01-01
1  2  4.5 2000-01-02

In [16]:
df.to_numpy()

array([[1, 3.0, Timestamp('2000-01-01 00:00:00')],
       [2, 4.5, Timestamp('2000-01-02 00:00:00')]], dtype=object)