In [6]:
import pandas as pd
import numpy as np

In [ ]:
pandas.Index.duplicated

Index.duplicated(keep='first')

Indicate duplicate index values.

Duplicated values are indicated as True values in the resulting array.

Either all duplicates, all except the first, or all except the last occurrence of duplicates can be indicated.

keep: {'first', 'last', False}, default 'first'
The value or values in a set of duplicates to mark as missing.

'first' : Mark duplicates as True except for the first occurrence.
'last'  : Mark duplicates as True except for the last occurrence.
False   : Mark all duplicates as True.

In [8]:
idx = pd.Index(['lama', 'lama', 'lama', 'lama', 'lama'])
idx

Index(['lama', 'lama', 'lama', 'lama', 'lama'], dtype='object')

In [10]:
idx.duplicated()

array([False,  True,  True,  True,  True])

In [12]:
idx.duplicated(keep='first')

array([False,  True,  True,  True,  True])

In [14]:
idx.duplicated(keep='last')

array([ True,  True,  True,  True, False])

In [16]:
idx.duplicated(keep=False)

array([ True,  True,  True,  True,  True])