In [2]:
import pandas as pd
import numpy as np

In [ ]:
pandas.Index.factorize
Index.factorize(sort=False, use_na_sentinel=True)
Encode the object as an enumerated type or categorical variable.



In [52]:
codes, uniques = pd.factorize(np.array(['b', 'b', 'a', 'c', 'b'], dtype="O"))

In [54]:
codes

array([0, 0, 1, 2, 0])

In [10]:
uniques

array(['b', 'a', 'c'], dtype=object)

In [48]:
codes, uniques = pd.factorize(np.array(['b', 'b', 'a', 'c', 'b'], dtype="O"),sort=True)

In [50]:
codes

array([1, 1, 0, 2, 1])

In [16]:
uniques

array(['a', 'b', 'c'], dtype=object)

In [38]:
codes, uniques = pd.factorize(np.array(['b', None, 'a', 'c', 'b'], dtype="O"))
codes

array([ 0, -1,  1,  2,  0])

In [ ]:
uniques