In [1]:
import pandas as pd
import numpy as np

In [ ]:
pandas.Index.isna

Index.isna()

Detect missing values.
    
Return a boolean same-sized object indicating if the values are NA. NA values, such as None, numpy.NaN or pd.NaT, get mapped to True values.

Everything else get mapped to False values.

Characters such as empty strings '' or numpy.inf are not considered NA values.


In [2]:
idx = pd.Index([5.2, 6.0, np.nan])
idx

Index([5.2, 6.0, nan], dtype='float64')

In [3]:
idx.isna()

array([False, False,  True])

In [4]:
idx = pd.Index(['black', '', 'red', None])
idx

Index(['black', '', 'red', None], dtype='object')

In [5]:
idx.isna()

array([False, False, False,  True])

In [6]:
idx = pd.DatetimeIndex([pd.Timestamp('1940-04-25'),pd.Timestamp(''), None, pd.NaT])
idx

DatetimeIndex(['1940-04-25', 'NaT', 'NaT', 'NaT'], dtype='datetime64[ns]', freq=None)

In [7]:
idx.isna()

array([False,  True,  True,  True])