In [1]:
import pandas as pd
import numpy as np

In [ ]:
pandas.Index.searchsorted
Index.searchsorted(value, side='left', sorter=None)

Find indices where elements should be inserted to maintain order.

Find the indices into a sorted Index self such that, if the corresponding elements in value were inserted before the indices, the order of self would be preserved.

value
array-like or scalar

side
{‘left’, ‘right’}, optional
If ‘left’, the index of the first suitable location found is given. 
If ‘right’, return the last such index.
If there is no suitable index, return either 0 or N (where N is the length of self).
                                                                                                                                                                 
sorter
1-D array-like, optional

In [2]:
ser = pd.Series([1, 2, 3])
ser

0    1
1    2
2    3
dtype: int64

In [10]:
ser.searchsorted(4)

np.int64(3)

In [4]:
ser.searchsorted([0, 4])

array([0, 3])

In [5]:
ser.searchsorted([1, 3], side='left')

array([0, 2])

In [14]:
ser.searchsorted([1, 3], side='right')

array([1, 3])

In [15]:
ser = pd.Series(pd.to_datetime(['3/11/2000', '3/12/2000', '3/13/2000']))
ser

0   2000-03-11
1   2000-03-12
2   2000-03-13
dtype: datetime64[ns]

In [16]:
ser.searchsorted('3/14/2000')

np.int64(3)

In [17]:
ser = pd.Categorical(
    ['apple', 'bread', 'bread', 'cheese', 'milk'], ordered=True
)
ser

['apple', 'bread', 'bread', 'cheese', 'milk']
Categories (4, object): ['apple' < 'bread' < 'cheese' < 'milk']

In [18]:
ser.searchsorted('bread')

np.int64(1)