In [2]:
import pandas as pd
import numpy as np

In [128]:
pandas.Index.asof_locs
Index.asof_locs(where, mask)

As in the pandas.Index.asof(), if the label (a particular entry in where) is not in the index, the latest index label up to the passed label is chosen and its index returned.

If all of the labels in the index are later than a label in where, -1 is returned.

mask is used to ignore NA values in the index during calculation.

where : Index
An Index consisting of an array of timestamps.

mask : np.ndarray[bool]
Array of booleans denoting where values in the original data are not NA

In [130]:
idx = pd.date_range('2023-06-01', periods=3, freq='D')
where = pd.DatetimeIndex(['2023-05-30 00:12:00', '2023-06-01 00:00:00','2023-06-02 23:59:59'])
mask = np.ones(3, dtype=bool)

In [131]:
idx

DatetimeIndex(['2023-06-01', '2023-06-02', '2023-06-03'], dtype='datetime64[ns]', freq='D')

In [132]:
where

DatetimeIndex(['2023-05-30 00:12:00', '2023-06-01 00:00:00',
               '2023-06-02 23:59:59'],
              dtype='datetime64[ns]', freq=None)

In [133]:
mask

array([ True,  True,  True])

In [134]:
idx.asof_locs(where, mask)

array([-1,  0,  1])

In [135]:
mask[1] = False
idx.asof_locs(where, mask)

array([-1,  0,  0])