In [1]:
import pandas as pd
import numpy as np

In [ ]:
pandas.Index.get_indexer_for

Index.get_indexer_for(target)

Guaranteed return of an indexer even when non-unique.

This dispatches to get_indexer or get_indexer_non_unique as appropriate.

In [2]:
idx = pd.Index([np.nan, 'var1', np.nan])
idx

Index([nan, 'var1', nan], dtype='object')

In [5]:
idx.get_indexer_for([np.nan])

array([0, 2])

In [ ]:
#My Contribution

In [14]:
index = pd.Index(list('samsheer'))
index

Index(['s', 'a', 'm', 's', 'h', 'e', 'e', 'r'], dtype='object')

In [16]:
index.get_indexer_for(['s','h'])

array([0, 3, 4])

In [17]:
index.get_indexer_for(['s','h', 'e'])

array([0, 3, 4, 5, 6])