In [2]:
import pandas as pd
import numpy as np

In [6]:
mi = pd.MultiIndex.from_arrays([list('abb'), list('def')])
mi

MultiIndex([('a', 'd'),
            ('b', 'e'),
            ('b', 'f')],
           )

In [10]:
mi.get_locs('b')

array([1, 2])

In [14]:
mi.get_locs([slice(None), ['e', 'f']])

array([1, 2])

In [16]:
mi.get_locs([[True, False, True], slice('e', 'f')])

array([2])